bitcoin-core/bitcoincore.org

_includes/releases.html

The list items appear smaller because they are no longer `h3`.
[new vs old]

Fix <li> syntax

---

_sass/page.scss

Most pages noways have a line-height of >1em.
Using a line height of 1.5em makes things more readable.
Before:
After:

Use 1.5em line height

---

_posts/en/posts/2015-12-14-segregated-witness.md
_posts/en/posts/2016-01-13-developer-visualisation-2015.md

Markdown link don't appear to be rendering with auto excerpts in the `/` or `/bog/`.

Fix excerpts

---

_data/navigation.yml
_includes/_navigation.html
_sass/page.scss

With the new back design from #27:

Add support for nested menus

---

.travis.yml

@btcdrak discovered that Travis CI blacklists the `gh-pages` branch by default, so he added it to the CI whitelist.  Unfortunately, if you use the whitelist at all, no non-whitelisted branches get built (unless you open a PR to a whitelisted branch).
This commit uses Travis's [regex feature](https://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions) to whitelist all branches.  I tested it on my GitHub fork and it [seems to work](https://github.com/harding/website/branches).

[Trivial] Travis CI all branches

---

_data/navigation.yml
_posts/en/pages/2016-01-13-segwit-support.md

Add segwit adoption page

---

README.md
_config.yml
_data/authors.yml
_includes/_author-bio.html
_layouts/home.html
_layouts/post-index.html
_layouts/post.html
_sass/vendor/google/_fonts.scss

* Forces fonts to load over HTTPS
* Updated jekyll configuration to twitter cards and OpenGraph to point to the new twitter accounts
* Fixed homepage and blog-index pages to strip markdown syntax from excerpts
* Added h-entry CSS classes to blog post template to opt-in to [Firefox reader mode](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages) to improve accessability to tools like [Pocket](https://getpocket.com), [Instapaper](https://instapaper.com) and text-to-speech readers.
* :tada:

Accessibility improvements

---

CONTRIBUTING.md

Code and documentation that make this website are licensed under MIT
Content published on the website suggested [CC-by-SA](http://creativecommons.org/licenses/by-sa/4.0/) which is the most permissive version.
#8

Update CONTRIBUTING.md with licensing information

---

.gitignore
_posts/en/meetings/2016-03-03-meeting.md

@G1lius is on vacation this week, as noted in one of this earlier meeting notes, so I volunteered to write this week's summary.  A preview may be seen here: http://dg0.dtrt.org/en/meetings/2016/03/03/
In addition to the meeting summary, I also added the directory used by Jekyll for incremental rebuilds to the `.gitignore` file.
Please let me know if the summary needs any formatting or other changes, or if there's anything I should do differently for next week.  Thanks.

Meeting summaries: 2016-03-03

---

_data/navigation.yml
_data/source_navigation.txt
_includes/_references.md
_includes/pages/list/announcement.html
_posts/en/pages/2016-03-12-contact.md
_posts/en/pages/list/2016-03-10-announcements-join.md
_posts/en/posts/2016-03-12-announcelist.md
_posts/en/posts/2016-03-15-announcelist.md
_posts/misc/list/announcements/2016-03-10-check.md
_posts/misc/list/announcements/2016-03-10-confirmed.md
_posts/misc/list/announcements/2016-03-10-unsub.md
_sass/page.scss

Improve communications by providing an opt-in email list for security and release notifications. Requested by many people who don't have time to follow social media or other noisier channels. This list is only for Bitcoin Core security/release announcements.

Add announcement list

---

_includes/_references.md
_posts/en/meetings/2016-03-10-meeting.md

Last week's meeting summary. A preview may be seen here: http://dg0.dtrt.org/en/meetings/2016/03/10/ 
I believe @G1lius should be back for this Thursday's (3/17) meeting.
@btcdrak regarding your comment from last week about separate subheads for background, meeting comments, and conclusion to make the notes more skimable, I think it's not good typesetting to have subheads with fewer than three paragraphs between them so I didn't add them.  However, this week I did use standout formatting to try to accomplish the same thing: background is placed in italics; meeting comments are unstyled; and the conclusion begins with the phrase "Action item(s):" in bold.
As always, please let me know if there's anything I can improve.  Thanks!

Meeting summaries: 2016-03-10

---

_posts/en/pages/2016-01-18-segwit-wallet-dev.md

Fixed a typo in the segwit wallet dev guide where it said that p2wsh outputs used ripemd160(sha256(witnessScript)) instead of the actual sha256(witnessScript)

Fix typo in segwit dev guide

---

_posts/en/pages/2016-03-12-contact.md

We get too many support queries. I thought this was already mentioned on the site but it wasn't.

contact: security alias is not for support

---

_posts/en/pages/2016-01-15-lifecycle.md

There has been repeated confusion about Bitcoin Core's release versioning compared with SemVer 2.0.0.
While Bitcoin Core does indeed follow the spirit of SemVer regarding major and minor releases, where minor releases focus on bug fix maintenance; Bitcoin Core software releases are decoupled network versioning and consensus rule changes. As such, the exceptions need to be explained explicitly.

Update lifecycle page

---

_posts/en/posts/2016-06-24-segwit-next-steps.md

This adds a blog post describing the current state of segwit, how it is expected to be rolled out, and a few things that are possible in future Script upgrades.  It is based upon an outline written (I believe) by @btcdrak and contains many suggested improvements to an earlier draft from a number of people.  All remaining errors are entirely my fault.
A screenshot of the rendered post can be found here: https://i.imgur.com/NOhsA9i.png
The document is long, so time-pressed Bitcoin experts who only have time to review part of it are encouraged to start with the last two sections, "Schnorr" and "MAST", as those are the topics I knew the least about and which seemed to have the most significant errors found during first review.
I feel the MAST section is the weakest part of the blog post and …

Blog: add "Segregated Witness: Next Steps"

---

_posts/zh_CN/pages/2016-01-01-contribute.md
_posts/zh_CN/pages/2016-01-13-segwit-support.md

A couple of the zh-CN translations have name: fields that include a date and thus don't match the english header, so the language drop down doesn't work right.

Fix name: header for zh-CN translations

---

_data/segwitsupport.csv
_includes/pages/segwit_support.md
_posts/en/pages/2016-01-13-segwit-support.md
_posts/zh_CN/pages/2016-01-13-segwit-support.md
_sass/page.scss
_sass/variables.scss

Here's a patch to add background colours to the segwit adoption table -- makes it a bit easier to spot which ones aren't done yet. Not sure if there's a meaningful difference between "wip" and "no"; I left "wip" as normal background but maybe it should be coloured "bad" too.
I couldn't get kramdown markup to add an attribute to cells, so switched to using liquid to generate HTML directly based on a CSV file, which seems fine. I chose yellow and blue because it seems to work for colour blind (unlike green and red), doesn't suffer from red is bad in the West and good in the East confusion, and because "golden" sounds positive and "blue" is sad, but whatever.
Also added a URL for NBitcoin since it was the only one missing a URL and it saved special casing it.

Colourise segwit adoption table

---

_posts/en/posts/2016-01-26-segwit-benefits.md

As it turns out, segwit's commitment structure isn't extensible enough to be reused to allow compact fraud proofs [1] [2]. So I think this section should be removed from the page, and here's a patch to do so.
[1] From #bitcoin-core-dev irc:
>  <aj> question: re: https://bitcoincore.org/en/2016/01/26/segwit-benefits/#compact-fraud-proofs -- as it turns out, that didn't make it in, right? those will need an additional merkle tree with an additional coinbase commitment with segwit as implemented, just as they would without segwit, yes/no?
> <gmaxwell> aj: right, or get picked up as part of some other addition that needs an additional commitment.
> <gmaxwell> it can be done with 'external commitments' in the same manner as the proposed commited bloom filters... meaning that it's possible to …

segwit-benefits: remove compact fraud proofs

---

_data/navigation.yml
_posts/en/pages/2016-10-26-segwit-upgrade-guide.md
assets/images/filtering-by-upgraded-node.svg

This adds a guide to upgrading (or not upgrading) to segwit for miners, node operators, wallet users, and Bitcoin devs.  
- A link to this guide is added to the FAQ menu.
- A link is *not* added to the main page, as it seems like we'll be adding a link there soon enough for the 0.13.1 release.
- All Markdown reference-style links to this document are defined, as verified by searching the rendered document for the string `][` that is indicative of an undefined link.
- It is expected that the release blog for 0.13.1 will link to this document; however, I think it is safe to merge this document prior to the release if everyone is ok with it's content (which is why it's in a separate PR from the upcoming PR for the release blog).
A preview screenshot may be found here: …

Add segwit upgrade guide

---

_posts/en/posts/2016-10-31-release-0.13.1.md
_posts/en/releases/2016-10-31-release-0.13.1.md

This adds a release blog post for 0.13.1.
**TODO**
---
A preview for the blog post as of fd373869eab2e473c7953efe3098d2d604a2f9c3 may be found at: http://imgur.com/a/gKi9W
The post entry on the main page looks like this:
Please note that if you attempt to generate a preview of this document, you will need to add `--future` to Jekyll's parameters because the post is dated for 2016-10-31.
Several people provided suggestions on this in draft form, for which I am very grateful. Any errors that appear in this version are entirely my fault.  For anyone who read the final draft version, I've made a few small changes:
1. I further shortened some of the descriptions in the new features summary section at the top.  The only significant phrasing change is in point 7 (More efficient almost-full-node …

Add release blog post for 0.13.1

---

.travis.yml
README.md

In https://github.com/bitcoin-core/bitcoincore.org/pull/241#issue-185549835 I mentioned that the Travis CI tests were passing when they were expected to fail.  This commit resolves that issue.
The problem was that pull request included a page with a future date and the previous Travis configuration didn't build or test pages with future dates.  As of this commit, Travis should build all possible pages (as best I can tell from `jekyll build --help`) so that they are all tested.

Travis: build all possible pages for testing

---

_includes/_references.md
_posts/en/meetings/2016-10-27-meeting.md

The following line from the meeting,
```
15:09 < harding> btcdrak: https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2016-October/000023.html
```
was attributed to Tom Harding, who uses the nick `dgenr8` rather than to me.  I'm not sure pasting a link is noteworthy enough to be included as a "participant", but this commit corrects the attribution anyway.
Thanks to /u/thorjag on Reddit for [pointing this out](https://www.reddit.com/r/Bitcoin/comments/5as3mu/bitcoin_core_irc_meeting_summary_october_27_2016/d9jn732/).  
@G1lius sorry for the confusion.  In case it helps in the future, there is an IRC command, `/whois` that will display information about a user, including a real name that the user can optionally set.  (On Freenode, I think you need to be in at least one of the same …

Meeting notes 2017-10-27: correct attribution for harding

---

_data/segwitsupport.csv

This PR is to signal Gemini's readiness on https://bitcoincore.org/en/segwit_adoption/
I am submitting this in my capacity as a Gemini Software Engineer.

Add Gemini to segwitsupport.csv

---

_data/segwitsupport.csv

Ciphrex would like to use the company name rather than the name of one of our products in the adoption page. In addition, it should be listed as a library as well as a wallet.

Use Ciphrex for name in adoption page rather than mSIGNA.

---

_data/segwitsupport.csv

If possible, would be nice if you could add our service, because we are big fans of core & segwit.
We also announced our segwit + core support in our news announcements (https://bitcoinreminder.com, look at the left side)

Add bitcoinreminder.com to segwitsupport.csv

---

_posts/en/meetings/2017-03-23-meeting.md

In writing the notes, I misinterpreted the colorized logs and gave the wrong attribution for this quote.  I guess it's back to reading raw logs in `less` for me.

Meetings: fix quote attribution in 2017-03-23 meeting

---

_includes/pages/bips-list.md

[BIP152](https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki) (compact block relay) was [implemented in 0.13.0](https://bitcoincore.org/en/releases/0.13.0/#compact-block-support-bip-152).

Add BIP152 to implemented list

---

_posts/en/posts/2017-04-22-release-0.14.1.md
_posts/en/releases/2017-04-22-release-0.14.1.md

Release blog post is just the Notable Changes section of the release notes with some introduction and conclusion boilerplate bolted on, and a couple minor edits.

Release blog & notes for 0.14.1

---

_data/segwitsupport.csv

Armory's latest release, 0.96.0, has all segwit functionality but is hard coded to be disabled on the mainnet. This will be changed in another release to enabled once segwit is activated or until we finish BIP 9 soft fork detection. I think that is enough to mark it as ready.

Update Armory segwit status to Ready

---

_data/navigation.yml
_posts/en/pages/2017-01-01-twitter-impersonation.md

In https://github.com/bitcoin-dot-org/bitcoin.org/issues/1842 @midnightmagic requested a page explicitly mentioning the Twitter impersonation accounts are fake.  This PR adds a short statement to that effect, including mentioning Bitcoin Core's official twitter account.
The page is added to the Contact menu:
Note that I reported one of the accounts (*@BcoreProject*) to Twitter about a month ago and it's still there, so I'm not sure we can expect much action from Twitter on this issue.

Pages: add new page about Twitter Impersonation

---

_posts/en/pages/2017-01-01-twitter-impersonation.md

Twitter impersonation page's name description is duplicate with Contact page. 
So language pulldown shows duplicate menu.

Fix name duplication

---

_posts/en/pages/2016-01-01-meetings.md

A few people have asked about the out-of-date meeting list in IRC recently. This adds a note to the page with a link to the minutes and logs produced by the meeting bot.

Add link to meeting bot logs

---

_includes/templates/download.html

Requested by @MarcoFalke in https://github.com/bitcoin-core/bitcoincore.org/pull/452#pullrequestreview-70759560
I confirmed using a local preview that the current link points to https://github.com/bitcoin/bitcoin/releases/tag/v0.15.0.1
Not implemented is @MarcoFalke's suggestion to change the text associated with the link.  I think "source code" is more understandable to most people than "git source".  If there is still a desire to change the text, I'm happy to do that.

Download page: change "source code" link to current tag

---

_posts/en/posts/2018-02-26-release-0.16.0.md
_releases/0.16.0.md

Preview: http://dg0.dtrt.org/en/2018/02/26/release-0.16.0/
This PR contains a blog post for the 0.16.0 release that is mostly a copy of the release notes.  I've replaced the release notes introduction with a more blog-like introduction, removed the PR-by-PR changelog and credits, and made some minor edits mainly for formatting (e.g. `text in backtics` in subheads doesn't render well in the table of contents).  Links are provided in the blog post to the download page and full release notes.
A diff between the actual release notes and the blog file is concise enough for easy review for anyone who wants to check my work.
diff -u _releases/0.16.0.md _posts/en/posts/2018-02-26-release-0.16.0.md | colordiff | less -R
I've also added the magnet URI to the release file so the magnet link shows up …

Blogs: post for 0.16.0 release

---

_includes/_navigation.html

at 0a55519 commit, Collection is used for release articles, and the release article link is no longer included in the header navigation link (navigation link has only post articles), so fix it.

Fix navigation link

---

_includes/_references.md
_posts/en/meetings/2017-05-11-meeting.md
_posts/en/meetings/2018-04-19-meeting.md

Preview: http://dg1.dtrt.org/en/meetings/2018/04/19/
In addition to adding this week's notes, changes the attribution for @Xekyo's comments in a previous meeting from "Murch" to "Mark Erhardt" (the name in his GitHub profile); this is done for consistency with the attribution used in these meeting notes.

Meetings: add 2018-04-19

---

_config.yml

HTML diff of generated site: https://dtrt.org/tmp/analytics-diff.html
This appears to have been enabled in 0364786e04566b9b7b53f739632beaadc70032a6 without a PR or any public discussion that I can [find](https://github.com/bitcoin-core/bitcoincore.org/search?utf8=%E2%9C%93&q=analytics&type=), so I have some questions:
- Is this currently being used?  By whom and for what?  (E.g., when analytics was enabled on Bitcoin.org, it was supposed to be used as a trustworthy source of visitor statistics in order to solicit advertisers.)
- Do we really want to be sending all of our visitor data to Google?  (I.e., if we need tracking for some reason, can we get that data instead from the server logs?)
- Do we really want Google to be able to inject Javascript onto our pages?  (E.g., being able to …

All pages: disable Google Analytics

---

README.md

Closes #525 ; CC: @karel-3d 
Links to the website and documentation for the upstream of the theme we use.  We haven't upgraded the files related to the theme since the website went live in Jan 2016, so I also mention that the current documentation might not completely match the theme files/settings.

Readme: mention theme used and link to its documentation

---

_includes/_references.md
_includes/dev-keys.md
_includes/fingerprint-split.html
_posts/en/pages/2016-03-12-contact.md
_posts/en/pages/list/2016-03-10-announcements-join.md
_posts/en/posts/2016-03-15-announcelist.md

Closes #543 ; CC: @kallerosenbaum
Updated bottom section on Announcement list page looks like:
---
New bottom section on updated Contact page looks like:
---
Translations of the two pages don't have any text changed, but the links for the three keys are redirected to the pgp.mit.edu keyserver web interface as suggested in the corresponding issues (pgp.mit.edu is slow, but at least it doesn't 404).  When those pages are re-translated with the updated content, we can remove the old links directly to the keys.
I obtained the key fingerprints from [here](https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-keys/keys.txt) but haven't otherwise validated them, so somebody who has checked them should probably review this PR.

Contact & Announcement List pages: update GPG key links & provide fingerprints

---

_releases/0.16.1.md

Fixed the release type in 0.16.1 release notes from `major` to `minor`.

Fix wrong release type in 0.16.1 release note

---

_sass/page.scss

Preview: http://dg1.dtrt.org/en/download/
On the live BitcoinCore.org site, if you hover your mouse over one of the expandable sections in the Download Page verification docs, it shows the default mouse cursor (mouse not pictured in image below).
With this commit, the cursor is changed to the cursor used for clicking on a link (e.g. a hand with pointer finger extended).  I've tested this works using a Chromebook running the Chrome browser (on my usual OS, nothing in any browser seems to change the cursor).
Suggested by Daniel E. Renfer, duck1123, [on Twitter](https://twitter.com/duck1123/status/1008013971830509568)

[Trivial] Download page: make expandable sections use clickable mouse cursor

---

_releases/0.16.0.md

Display bug on https://bitcoincore.org/en/releases/0.16.0/ :   
Fixed by putting the sighash name in `code quotes`

[Trivial] Releases: fix overzealous tablification in 0.16.0 notes

---

_releases/0.16.0.md

While doing my final checks before pushing the merge of #573, I noticed another formatting error in the 0.16.0 release docs due to the difference between GitHub Markdown and this site's Kramdown Markdown.  Before this PR:
With this PR:
I did a check of the *whole* document this time to make sure there are no other obvious formatting problems.  I also confirmed that the 0.16.0 release notes in the bitcoin/bitcoin repository render without these problems on GitHub.
Sorry for the noise.

[Trivial] Add required missing whitespace to 0.16.0 release notes

---

_includes/references.md
_posts/en/posts/2018-07-29-release-0.16.2.md
_releases/0.16.2.md

Adds release notes and a short blog post.  Previews:
- Blog: http://dg0.dtrt.org/en/2018/07/27/release-0.16.2/
- Release notes: http://dg0.dtrt.org/en/releases/0.16.2/
- Download page: http://dg0.dtrt.org/en/download/
Todo:
- `_releases/0.16.2.md` - change date in YAML header
- `cd _posts/en/posts/ ; rename 's/.*release/'$(date -u -I)'-release/' _posts/en/posts/2018-07-27-release-0.16.2.md ; git add .`
Note: this PR is expected to fail Travis CI as it expects the binaries to be in /bin/, which they're not yet.  The CI should pass once if Travis is restarted after the binaries are in their final location.

Releases: add 0.16.2

---

Makefile

In 0e7d61a91452d7a30577831a118873355514e593, I broke the HTML proofer test.  Sorry.  It still generated warning messages but it always returned true, even when something was broken.  Happily, we didn't manage to break anything.
This fixes the test.  Unlike before, I've tested that this does actually cause make (and thus Travis) to fail on broken content.

Tests: fix ignored return value from htmlproofer

---

_posts/en/posts/2018-09-18-release-0.16.3.md
_releases/0.16.3.md

Adds release notes (which updates Download page) and a short announcement blog post (which gets linked from the home page).  Note: tests are expected to fail because the binaries are not uploaded yet; they should pass if restarted after the binaries are available.
TODO:

Releases: add 0.16.3

---

_releases/0.16.3.md

We didn't receive any user reports that the magnet URI was broken, so it seems to have worked just fine with the other trackers.  (I noticed the extra newline while prepping the 0.17.0 release notes.)

Releases: 0.16.3: remove accidental newline in magnet URI

---

assets/elements/sitemaps.xml

The current `sitemap.xml` is generated only using the contents of the `_posts` directory, meaning it excludes the release notes (`_releases`) and RPC docs (`_docs`).  This 4-line diff updates it to include all of the site's [Jekyll collections](https://jekyllrb.com/docs/collections/) by iterating over the `site.collections` array that includes `_posts` and everything else.
This still omits URLs on the site that aren't part of any collection and which Jekyll stores in the `site.pages` array.  Right now, this entirely consists of content not intended for direct human reading, like CSS and redirect files, which shouldn't be part of the sitemap anyway.  If that changes in the future (and I'd like it to), I'll have to update the sitemap again---but the old version of Jekyll we use now doesn't …

Update sitemap to include releases & RPC docs

---

_releases/0.17.0.1.md

Preview: http://dg1.dtrt.org/en/releases/0.17.0.1/ & http://dg1.dtrt.org/en/download/
Todo:
Both can be safely done after the merge, if desired.
Release notes include an extra sentence not in the original and a link to the 0.17.0 release notes, as discussed earlier today on IRC.
Note: Travis build expected to fail until binaries have been uploaded.

Releases: add 0.17.0.1

---

_includes/head.html
_includes/open-graph.html
_layouts/doc.html
_layouts/page.html
_layouts/post-index.html

When we use HTML directly (not through parsed Markdown), XML entities need to be escaped.  Our tests catch cases where that doesn't happen, so we don't need to be fastidious about it, but in this case I was trying to add a page with an ampersand in the title and these were the places where the tests complained.
Verified via a diff of the rendered site compared to master that this produces no changes in the rendered site for all current content.

HTML: xml escape page titles

---

_posts/ja/pages/2016-01-18-segwit-wallet-dev.md

Uses correct name of `scriptPubKey` in Japanese version of `2016-01-18-segwit-wallet-dev.md`.
On transifex I requested to join the Japanese language in the bitcoincore.org team.
Are transifex translations still relevant?

Uses correct name of scriptPubKey in Japanese version of 2016-01-18-segwit-wallet-dev.md.

---

_includes/templates/download.html
_posts/en/pages/2017-01-01-download.md

Recently, @laanwj's release signing key expired.  He has uploaded to key servers an updated key with a future expiration date, but the copy of the key hosted on this server is still the expired version.  Instead of updating it, this drops the link to it on the Download page and also adds a tiny note about `gpg --refresh-keys`  Preview (bottom text):
The verification instructions on the page all mention getting the key with `--recv-keys` and there are no other links to the key on this site, so I think this is an acceptable solution.  However, this PR leaves the actual expired key on the site in case any third party scripts are grabbing it automatically and just ignoring its expired status.

Download page: remove link to laanwj's key; mention --refresh-keys

---

_includes/pages/list/announcement.html
_posts/en/pages/2016-03-21-rss.md
_posts/en/pages/list/2016-03-10-announcements-join.md
_posts/en/posts/2016-03-15-announcelist.md
_posts/en/posts/2018-02-26-release-0.16.0.md
_posts/en/posts/2018-06-15-release-0.16.1.md
_posts/en/posts/2018-07-29-release-0.16.2.md
_posts/en/posts/2018-09-18-release-0.16.3.md
_posts/en/posts/2018-09-20-notice.md
_posts/en/posts/2018-10-02-release-0.17.0.md
_posts/ja/pages/list/2016-03-10-announcements-join.md
_posts/zh_CN/pages/list/2016-03-10-announcements-join.md
en/announcements.xml

I've been unable to contact @btcdrak, the administrator of the security and releases announcement mailing list, and it doesn't seem to be sending emails (certainly not reliably).  It'd be nice to set up a replacement, but right now other existing Bitcoin mailing lists are also in flux so there's no stable hosting available without creating a new dedicated solution.
This PR provides an alternative news source by recommending users follow an RSS feed for posts on the website tagged as announcements.  This isn't as good as email, but I think it's better than nothing (and certainly it's better than recommending people join a broken list).
Preview feed: http://dg0.dtrt.org/en/announcements.xml
Preview sign up page (menu->Contact->Announcements): http://dg0.dtrt.org/en/list/announcements/join/ …

Change announcements mailing list to RSS (at least temporarily)

---

_posts/en/posts/2018-12-25-release-0.17.1.md

Just adds 0.17.1 to the [new feed](https://bitcoincore.org/en/announcements.xml).  This should've been done as part of the final rebase of #610 but I forgot to git commit it.  :man_facepalming:

Announcements: add 0.17.1 to announcements RSS feed

---

_includes/templates/download.html

Set win64 as default for windows users.
It has better performance, supports higher dbcache values, and so on.
Surprised this wasn't the case already.

releases: Change windows default to win64

---

contrib/qa/test-binary-availability.sh

While testing #653, I discovered that the `test-binary-availability.sh` test failed locally even though it succeeded on Travis.  The test was looking for HTTP/1.1 success codes but my local `curl` was retrieving the Snapcraft page via HTTP/2 and printing a slightly different success message.  This updates the test to accept either success message.

Tests: handle offsite URLs that use HTTP/2 with recent versions of curl

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

People sometimes mistakenly open issues against this repo for requested changes to bitcoin.org, eg:
- https://github.com/bitcoin-core/bitcoincore.org/issues/660
- https://github.com/bitcoin-core/bitcoincore.org/issues/652
Add templates for github issues and PRs to direct people to the right place.

Add templates for github issues and PRs

---

_config.yml
_includes/dev-keys.md
_includes/templates/download.html

Closes #667
Adds the parameters necessary for using the Ubuntu keyserver to each case where we describe how to download a key.  I put the string in the config file so it's easy to change or disable globally.  Also makes a small unrelated change to the heading id tag to hopefully address #668

Verification instructions: suggest keyserver

---

_includes/download_release.html
_releases/0.17.1.md
_releases/0.18.1.md
_releases/0.19.0.1.md
_sass/download.scss

We currently only show the torrent link on the download page, which only covers the most recent version.
This adds a torrent link on each release page:
I applied this to 0.19.0.1, 0.18.1 and 0.17.1; probably not worth doing it for older versions.

Add torrent link to release page

---

_posts/en/meetings/2016-09-15-meeting.md
_posts/zh_CN/posts/2016-01-28-clarification.md
_posts/zh_CN/posts/2016-08-23-release-0-13-0.md
_releases/0.13.0.md

Split from #686.
In anticipation of updating HTML proofer.
```
- ./_site/en/2016/08/23/release-0.13.0/index.html
*  linking to internal hash #change-log that does not exist (line 3698)
<a href="/en/releases/0.13.0/#change-log">hundreds of notable improvements</a>
- ./_site/en/meetings/2016/09/22/index.html
*  linking to internal hash #release that does not exist (line 3723)
<a href="/en/meetings/2016/09/15/#release">last weeks meeting</a>
- ./_site/zh_CN/2016/01/28/clarification/index.html
*  http://lists .linuxfoundation.org/pipermail/bitcoin-dev/ is an invalid URL (line 3687)
<a href="http://lists%20.linuxfoundation.org/pipermail/bitcoin-dev/">bitcoin-dev 电邮列表</a>
- ./_site/zh_CN/2016/08/23/release-0.13.0/index.html
*  href="https://github.com/bitcoin/bitcoin/issues/new is an invalid …
```

Repair broken links

---

_includes/navigation.html
_layouts/doc.html

Split from #686 
Also fixes the menu (this didn't work in a earlier version)

Sort RPC docs by descending version

---

_posts/en/pages/2016-01-18-segwit-wallet-dev.md
_posts/ja/pages/2016-01-18-segwit-wallet-dev.md

Fix #692 I will eventually solve the certificate issue on the real website, but in any case `blockchainprogramming.azurewebsites.net` should be more stable, as the site is actually hosted there.

Fix segwit example links

---

_data/stats.yml

The current actual estimate is 280 Gb.
Rounding up per instructions.

update estimated data directory size to 300 Gb

---

_posts/en/posts/2016-01-26-segwit-benefits.md

Since this feature is no longer viable in light of CVE-2020-14199, remove it from the page (as we did previously for compact fraud proofs).

Segwit benefits: Retire "Signing of input values" section

---

_posts/en/pages/2017-01-01-twitter-impersonation.md

This is a very simple merge. I noticed missing capitalization and just made a quick update.

Fixed missing capitalization on the twitter impersonation page title

---

_posts/en/pages/2016-01-01-meetings.md
_posts/en/pages/2020-08-01-meeting-summaries.md

Adds information about the project's multiple meetings to the existing meetings page (linked from the Development item on the top-bar navigation).  Moves the historic meeting summaries to a new page.

Meetings: add times for multiple meetings; move summaries to new page

---

_includes/references.md
_posts/en/pages/2016-01-01-about.md

Closes #718 
This creates a new link definition, rather than changing the old one, because the old one is used in two translations.

About page: link to all contributors, not just recent

---

_includes/head.html

Starting with the release of [Tor Browser 9.5](https://blog.torproject.org/new-release-tor-browser-95), websites can have their alternate .onion addresses advertised to Tor desktop users who have the 'Onion Location' option enabled.
Sites that add the .onion address advertisement HTTP header can prompt their visitors to switch to a version delivered using the Onion service for improved security.
Final result:

Add Onion-Location meta tag

---

_includes/head.html
_includes/js/main.js
_layouts/doc.html
_sass/elements.scss

This PR is addressing the problem of finding docs for one specific rpc command by its name. In the website one can not simply find his/her desired command in the menu. One should open all the parent categories (`Blockchain`, `Control`, etc) and then use Ctrl+F to find the command.
I have added a little javascript code to handle the string search between all commands and make this process much easier.

Add search bar for rpc docs

---

_posts/en/posts/2016-10-28-segwit-costs.md

This PR updates `linear` to `quadratic` based on my impression that the sighash scaling problem SegWit solves is on the order of O(n<sup>2</sup>) and that Segwit reduces the complexity to O(n).

Update scaling term

---

_plugins/githubify.rb
_releases/0.14.1.md

As mentioned today in #bitcoin-core-dev IRC, the release notes for 0.21.0 will include at least one reference to a PR that was merged in the new GUI repository.  laanwj said he'll put this in the notes as "gui/#nnnn", so this PR updates the plugin to handle that appropriately.
To eliminate conflicts, one historic release note is updated to change from using `/` as a separator between PRs to using `,` as the separator.  The comma is consistent with other release notes, such as that for 0.14.0.
This change should be forward compatible for other possible monotree repos as long as they're part of the bitcoin-core organization and the release notes use the format `<repo-name>/#<pr-number>`, e.g. `wallet/#123`.

Edit 0.14.1 release notes to separate multiple PRs with "," instead of "/"

---

_plugins/githubify.rb

There was a slight miscommunication about the expected format in #733, this uses the format from #734 as tested on the actual release notes:
I also quickly checked the HTML diff from before and after this change and I only saw one unwanted change (a link to an issue was dropped).  I think that's acceptable to keep the pattern simple.

Plugins: fix monotree repo ref from gui/#123 to gui#123

---

_posts/en/pages/2016-01-01-about.md

Fix #748, by replacing /bitcoin links with /bitcoin-core links, because everything Bitcoin Core related except the main repo has been moved to /bitcoin-core.

Solve redirecting GitHub links

---

contrib/doc-gen/generate.go

See Bitcoin Core PR https://github.com/bitcoin/bitcoin/pull/20987, in particular the discussion https://github.com/bitcoin/bitcoin/pull/20987#discussion_r562762266.
The recommended network for generating RPC docs is regtest, as stated in the script's file header comments:
```// (2) install bitcoin core, set it up to use regtest```
To achieve this, the user previosly needed to manually put `regtest=1` into
`~/.bitcoin/bitcoin.conf` -- the script didn't specify a concrete network, so
without config file setting, mainnet was used. With the change in this commit,
we will always connect to regtest by passing the `-regtest` option to the
`bitcoin-cli` invokation.
With this change, [harding's well-described way to use the script involving file editing via mighty …

RPC doc generating script: always connect to regtest

---

_posts/en/pages/2016-01-01-meetings.md

From what I understand, the P2P meeting will be held at 21:00 UTC from now on.

posts: Move P2P meeting to 21:00 UTC

---

_data/binaries.yaml

> There is currently no codesigning key available for Windows and to add insult to injury, Comodo revoked the old one. Until this can be resolved link the unsigned installer so that installation can at least continue with a big yellow warning.
> See bitcoin-core/gui#252.
Text above from #761 ; this is a simpler approach that updates all the links.  It can be reverted when the re-signed binary is uploaded.
In addition to this PR, I also checked that the shasums file is signed with @laanwj's usual key and that the hash of the -unsigned file is correct (I didn't check the other binaries).

Downloads: fix URL

---

_includes/references.md
_posts/en/pages/2016-01-01-contribute.md

- Remove mention of (retired) bitcoin-discuss list
- Remove mention of bitcoin-core-dev list under "discussion", as it has been changed into an [announcements list](https://bitcoincore.org/en/list/announcements/join/) and there was never any discussion there in the first place
- Add mention of other relevant IRC channels

Make contributing page up to date

---

_includes/download_release.html
_includes/templates/download.html
_posts/en/posts/2021-05-01-release-0.21.1.md
_releases/0.21.1.md

First commit drops links to the torrent (which hasn't been uploaded yet).  It'll be a clean revert of just that commit when the torrent is added.
Second commit adds a short blog post and the verbatim release notes.  Magnet link is commented out there until the torrent is available.
Preview here: http://dg1.dtrt.org/

Releases: add 0.21.1

---

_includes/references.md
_posts/en/pages/2016-01-01-contribute.md
_posts/en/pages/2016-01-01-meetings.md
_posts/en/posts/2016-01-28-clarification.md

Update website for the change of IRC servers. Change occurences of freenode in active (non-historical) documents to libera.chat. As libera has no official webchat, change the references to their main page for now.

Change freenode to libera

---

_posts/en/pages/2016-01-01-meetings.md

A long term fix will require some restructuring - I like the idea of mirroring in #772.
This can be accomplished thru a gh workflow for automation and easier maintenance.
In the mean time at least there will be a link to current meeting logs.

meetings log: temp fix for meetings link #772

---

_data/binaries.yaml
_posts/en/posts/2021-09-13-release-22.0.md
_releases/22.0.md

I hope the site can cope with the new version syntax.

Bitcoin Core 22.0

---

_includes/templates/download.html

This one-character patch temporarily hides the verification instructions, which have become out of date with the release of 22.0 and combined signature files.  See controlling issue #793 
An update to the instructions will require bumping the page version number and so automatically show the instructions again.

Downloads: hide verification instructions

---

_includes/templates/download.html
_posts/en/pages/2017-01-01-download.md

Fixes https://github.com/bitcoin-core/bitcoincore.org/issues/793.
This updates the binary verification instructions to account for the new process, which uses multiple builder signatures on the `SHA256SUMS` file. See https://github.com/bitcoin/bitcoin/issues/22634 for more details.

Update binary verification instructions for multiple signers

---

Makefile
_includes/templates/download.html

Ironically, @harding's comment in https://github.com/bitcoin-core/bitcoincore.org/pull/803#discussion_r712468502 was spot on. This fixes a lingering reference to `$(BUILDER_KEYS_TXT_URL)` in the macOS and Linux instructions.

download: fix outdated use of page.obtain_release_key

---

_includes/templates/download.html
_posts/en/pages/2017-01-01-download.md
_posts/ja/pages/2017-01-01-download.md

Guix is now the release process, and linking to gitian is at least
causing confusion, see https://github.com/bitcoin-core/docs/issues/76.

Link to guix.sigs repo rather than gitian sigs

---

_layouts/home.html

Fixes #488 
- Added published date to the recent posts

Recent posts to show published date

---

_posts/en/pages/2020-08-01-meeting-summaries.md

Since the name of the meeting page and summary page are the same `meetings`, multiple english pages will be displayed when opened in other languages.
This PR fix duplicate names.

Rename the meeting summary page to fix duplicate names

---

_includes/templates/download.html

The oldest supported macOS version is 10.12 which [can run](https://bitcoincore.org/en/releases/0.21.2/) Bitcoin Core 0.21.x.
Therefore, there are no "Mac OS X" or "OS X" among supported OSes from Apple (https://en.wikipedia.org/wiki/MacOS_version_history).

Replace outdated "Mac OS X" with a modern "macOS"

---

_data/navigation.yml

The dropdown doesn't lead to current relevant information for users. The FAQ is outdated now that
* segwit activated, (and taproot as well)
* opt-in rbf might be replaced by full-rbf
* versionbits was replaced by speedy trial

remove faq nav

---

_posts/es/posts/2021-09-29-release-0.21.2.md

Before this change, "Espanol" > "Bitcoin Core 0.21.2 liberado" links
a wrong page, the Japanese release notice.
Should fix issue #844.

Fix wrong link in translation es

---

_releases/0.20.2.md

Use
git blame _releases/0.20.2.md
to check 2021 as published date for this release post.

Fix year in release post

---

_includes/templates/download.html

Updated the path to the Windows GPG installation to reflect the latest version of Gpg4win: "C:\Program Files (x86)\GnuPG\bin\gpg.exe"

Update GPG4win path for easy user verification.html

---

_data/stats.yml

See: https://github.com/bitcoin/bitcoin/blob/dce93b2dd7a96398058cd7ef0044a3d48b608cba/src/chainparams.cpp#L110.

stats: increase assumed datadir size to 500GB

---

_posts/en/pages/2016-01-15-lifecycle.md

Update the text and examples in the lifecycle page to use the current versioning scheme.
Closes #872.

lifecycle: update text to current versioning scheme

---

_posts/en/pages/2016-01-01-meetings.md

This meeting is not regularly happening, and the last one was quite some time ago, remove its mention for now.

irc meetings: remove p2p meeting

---

README.md
logs/2016-05-zurich-meeting-notes.html

Cherry-picks two commits from #826 (which needs rebase, and is dependant on infra updates), which are correct, and can be merged now.

Cherry-pick part of 826

---

_layouts/home.html
_layouts/page.html
_layouts/post-index.html
_layouts/post.html

Prior to #863, an `article-author-side` sidebar ensured the main content was centered. This commit reintroduces the (empty) sidebar that #863 removed to fix the layout.
I have very little experience working with html/css so if there are more elegant solutions I'm open to that too, but this seems to revert to the old behaviour in a quite simple way.
Before:
After:

Re-add empty author sidebar to fix alignment

---

_posts/ja/releases/2022-12-12-release-24.0.1.md

There was one error in the description of the anchor link.

Fixup anchor link in japanese translation of 24.0.1

---

_posts/en/posts/2022-12-21-release-23.1.md
_releases/23.1.md

Add release pages for 23.1.
Same as https://github.com/bitcoin-core/bitcoincore.org/pull/869.

Bitcoin Core 23.1

---

_posts/en/pages/2017-01-01-download.md

Remove reference to "trusted release signing key". Squashed version of #894.

download: update verify_checksums_file string

---

_includes/templates/download.html
_posts/en/pages/2017-01-01-download.md
_posts/es/pages/2017-01-01-download.md

Closes #945 
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/957 (included)
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/807 (included)
Closes https://github.com/bitcoin-core/bitcoincore.org/pull/878
download + verify procedure tested on macOS and Linux. I will go through it again on Windows tonight and add one more commit for that.

Builder keys

---

_releases/26.0.md

Mirrors what is being done in https://github.com/bitcoin/bitcoin/pull/29023. Not for merge before that PR.

26.0: add missing release note fragments

---

_includes/dev-keys.md

The security contacts listed on the website differed from the SECURITY.md file in the bitcoin/bitcoin repo, they should be in sync.

Sync security contact keys with security.md

---

_posts/en/pages/2016-01-01-meetings.md

The wallet meeting was discontinued (IRC meeting 2023-05-11), and besides, the link here doesn't work.

Remove wallet meeting from meetings page

---

.cirrus.yml

The last version of bundle to support ruby 2.7.4 is 2.4.22. Should fix the current CI failure.

ci: Use bundler 2.4.22

---

_includes/templates/download.html
_posts/en/pages/2017-01-01-download.md

Picks up #892. This is a much more useful user experience.

Add `--ignore-missing` flag to `shasum` command on MacOS

---

_includes/templates/download.html

If a mac is detected by the browser, default to the ARM macOS download, rather than x86_64. This seems more reasonable at this point. In future, we might be able to use more advanced browser logic to detect the actual architecture dynamically. i.e https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues.

download: default to ARM macOS downloads over x86_64

---

_releases/27.1.md

Since the SHA256SUMS.asc had to be reuploaded, the torrent has also changed. The magnet url should be updated to match the torrent file.

release: Update 27.1 magnet url

---

_data/navigation.yml
_posts/en/pages/2024-06-26-disclosures.md

Add a new page summarizing the upcoming security advisory policy.

pages: add Security Advisories

---

_data/navigation.yml
_layouts/feed.xml
_layouts/home.html
_layouts/post-index.html
_layouts/rss.xml
_posts/en/pages/2024-06-26-security-advisories.md
_posts/en/posts/2018-09-20-notice.md
_posts/en/posts/2019-11-08-CVE-2017-18350.md
_posts/ja/posts/2019-11-08-CVE-2017-18350.md
en/announcements.xml

Followups to #1033.
* Ensure that both posts and advisories will be listed on the home/blog/other feeds.
* Rename some straggling instances of of disclosure to (security)-advisory.
* Add the missing menu item for translated pages (pointing to the en page for now).
* cc azuchi, you might be interested in following up with a  translation for the japanese page?

Security advisory followups

---

Makefile

Should help catch issues like those in #1042, which didn't cause the CI to fail.
```bash
bundle exec jekyll server --future --drafts --unpublished --incremental --strict_front_matter
...
Incremental build: enabled
Generating...
Error: YAML Exception reading /bitcoincore.org/_posts/en/posts/2024-06-10-disclose-bip70-crash.md: (<unknown>): mapping values are not allowed in this context at line 2 column 18
------------------------------------------------
```

build: add --strict_front_matter to build invocation

---

_releases/27.1.md

Not completely sure what the issue is, I guess we can't use the word Index, however this fixes the formatting of the release notes as currently shown on https://bitcoincore.org/en/releases/27.1/:

27.1: fix formatting in release notes

---

_posts/en/posts/2018-09-20-notice.md
_posts/en/posts/2019-11-08-CVE-2017-18350.md
_posts/en/posts/2024-07-03-disclose-bip70-crash.md
_posts/en/posts/2024-07-03-disclose-getdata-cpu.md
_posts/en/posts/2024-07-03-disclose-header-spam.md
_posts/en/posts/2024-07-03-disclose-inv-buffer-blowup.md
_posts/en/posts/2024-07-03-disclose-orphan-dos.md
_posts/en/posts/2024-07-03-disclose-timestamp-overflow.md
_posts/en/posts/2024-07-03-disclose-unbounded-banlist.md
_posts/en/posts/2024-07-03-disclose_already_asked_for.md
_posts/en/posts/2024-07-03-disclose_receive_buffer_oom.md
_posts/en/posts/2024-07-03-disclose_upnp_rce.md

This makes a number of changes to the titles and excerpts of the existing and new vulnerability disclosures:
* Use "Disclosure of [CVE number]" as title when a CVE is assigned.
* For vulnerabilities without known CVE put a very short description in the title.
* Drop latest version affected from the titles (it makes them too long, seeing it rendered).
* Include in the excerpts a short description of the vulnerability itself (but longer than the title), the date a fix was released, and in what version.
* Shorten all excerpts to no more than 160 characters (limit on homepage).
* Make titles/excerpts more uniform in style.

Make titles/excerpts of disclosures more uniform

---

_posts/en/posts/2024-07-31-disclose-addrman-int-overflow.md
_posts/en/posts/2024-07-31-disclose-upnp-oom.md

This publicly discloses 2 security vulnerabilities fixed in Bitcoin Core v22.0 and above.
These writeups result from a common effort to dig up and document past vulnerabilities with achow101 ajtowns fanquake dergoegge and sipa.

Security advisories for bugs fixed as of Bitcoin Core v22.0

---

_includes/js/main.js

This code calls a function that does not exist, resulting in a Javascript error on every page load.
[fitVids](http://fitvidsjs.com) is a jQuery plugin that probably was part of the codebase at some point (but definitely is not now).
I don't think there are any videos on the site. I also think that there are modern CSS-based approaches to resizing videos that could be implemented if necessary.

Remove fitVids function call

---

_layouts/doc.html

Since v22, the patch number is omitted in git tags, unless it is non-zero.
```
version  -> tag
0.21.0   -> v0.21.0
22.0.0   -> v22.0
24.0.1   -> v24.0.1
```
This breaks the "Documentation exported from Bitcoin Core 28.0.0" link on the RPC documentation page: https://bitcoincore.org/en/doc/28.0.0/ (and other >= v22 pages)
Fix this by automatically removing the patch if both the minor and patch numbers are zero. This creates some inconsistency in that on the same page we'll refer to both "28.0.0" and "28.0", but that seems unavoidable if we don't want to break permalinks.
Alternatives considered:
1. for affected version, update the `btcversion` field in existing RPC docs and in `generate.go`, but that would change a bunch of permalinks, making them not very perma
2. for affected versions, …

RPC docs: fix broken links to tags >= v22.0

---

_posts/en/posts/2024-10-08-disclose-blocktxn-crash.md
_posts/en/posts/2024-10-08-disclose-large-inv-to-send.md
_posts/en/posts/2024-10-08-disclose-mutated-blocks-hindering-propagation.md

This publicly discloses 3 security vulnerabilities fixed in Bitcoin Core v25.0 and above.

Security advisories for vulnerabilities fixed in v25.0

---

_posts/en/pages/2024-06-26-security-advisories.md

Clarify that low severity issues will be disclosed after a fix exists in the current major release branch.
For example, if an issue is fixed in master, and then released in v29.0, if would be pre-announced, at the time of the v29.0 release, and made public 2 weeks later.
If an issue was fixed in master, it could also be backported to the current release branch, i.e 28.x, and then be in the next release of that branch, i.e v28.1. In that case, it would be pre-announced with the v28.1 release, and made public 2 weeks later.

advisories: clarify low severity policy

---

_posts/en/posts/2024-11-05-cb-stall-hindering-propagation.md

There was one security vulnerability in 25.0 (and below) fixed in 26 (and 25.1). Thanks to Greg Sanders for writing up the advisory.
This is the last batch of historical disclosures. From now on we'll publicly disclose reported disclosures as per the policy.

Security advisories fixed in version 26

---

_posts/en/posts/2024-07-03-disclose-bip70-crash.md
_posts/en/posts/2024-07-03-disclose-getdata-cpu.md
_posts/en/posts/2024-07-03-disclose-header-spam.md
_posts/en/posts/2024-07-03-disclose-inv-buffer-blowup.md
_posts/en/posts/2024-07-03-disclose-orphan-dos.md
_posts/en/posts/2024-07-03-disclose-timestamp-overflow.md
_posts/en/posts/2024-07-03-disclose_already_asked_for.md
_posts/en/posts/2024-07-03-disclose_upnp_rce.md
_posts/en/posts/2024-07-31-disclose-addrman-int-overflow.md
_posts/en/posts/2024-07-31-disclose-upnp-oom.md
_posts/en/posts/2024-09-18-disclose-headers-oom.md
_posts/en/posts/2024-10-08-disclose-mutated-blocks-hindering-propagation.md
_posts/en/posts/2024-11-05-cb-stall-hindering-propagation.md

Only the `inv-to-send` advisory doesn't have one because there is a misunderstanding who claims it should be `CVE-2023-33297`. I explained it is an ID which was claimed by a troll on behalf of the project and i'm now awaiting their response. I don't think it should be a blocker to publish the other 13 IDs.

Update security advisories with recently assigned CVE IDs

---

_includes/references.md
_posts/en/pages/list/2016-03-10-announcements-join.md
_posts/ja/pages/list/2016-03-10-announcements-join.md
_posts/zh_CN/pages/2016-01-01-contribute.md

Mailing list link in: https://bitcoincore.org/en/list/announcements/join/ still points to the old linuxfoundation mailing list.
I found in the same file this other mailing lists that point to linuxfoundation, I'm not aware of them so I didn't touch, if there are new lists for them also, feel free to leave a comment and I can update all three in the same PR:
```
[bitcoin-discuss]: http://lists.linuxfoundation.org/mailman/listinfo/bitcoin-discuss
[bitcoin-dev]: http://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev
[bitcoin-core-dev]: https://groups.google.com/g/bitcoindev
```

update mailing list link

---

_releases/29.0.md

On the master branch @ 56264987d13d18d6a80678cb82bf676fb8a61b30, the code block is incorrectly rendered as a single line:
This PR ensures it is displayed correctly over three lines:
Numbering has been replaced with bullets, as the rendering engine otherwise restarts numbering from 1 after the code block.

Fix code block rendering in 29.0 Release Notes

---

_includes/templates/download.html

Change the default for ARM to the aarch64 download. 64-bit ARM is the standard nowadays for the type of computing hardware our users tend to have (Raspberri pi's and servers). While 32-bit ARM is only still used in low-power embedded systems.
Closes #1099.

Change ARM Linux default download to 64-bit

---

_posts/en/posts/2025-04-28-disclose-cve-2024-52919.md

I changed the URL of this post, but that was after it was posted to the mailing list, this has caused some amount of confusion. Add a redirect, so if anyone hits the original link, they'll end up in the right place.
See: https://groups.google.com/g/bitcoindev/c/v2mwcWtgfxM.

blog: add redirect for disclose-cve-2024-52919 post
