- _includes/_footer.html
- _layouts/post-index.html
- _sass/page.scss
> Different article/year-divider approach

- _posts/en/pages/2016-01-01-contribute.md
This has been a boring list. Now, there are two subsections and the senteces are connected.
> Format "Contribute"

- _sass/page.scss
> Bottom align logo with navigation

- _posts/en/posts/2016-01-13-developer-visualisation-2015.md
> [blog] Add commit visualisation for 2015

- _posts/en/posts/2016-01-13-developer-visualisation-2015.md
This video was re-rendered by @jonasschnelli
> Update video embed

- _posts/it/pages/2016-01-01-about.md
I have tried to stay on the same lines so it should be easier for review.
The title has been translated in "Chi Siamo" = "who we are" because there is not the corresponding page in italian sites. 
Normally "chi siamo" is used but I'm open to different ideas.
> Translation of about.html in Italian

- _data/navigation.yml
- _includes/_meetings.html
- _posts/de/pages/2016-01-01-meetings.md
- _posts/en/meetings/2015-10-01-meeting.md
- _posts/en/meetings/2015-10-08-meeting.md
- _posts/en/meetings/2015-10-15-meeting.md
- _posts/en/meetings/2015-10-22-meeting.md
- _posts/en/meetings/2015-10-29-meeting.md
- _posts/en/meetings/2015-11-05-meeting.md
- _posts/en/meetings/2015-11-12-meeting.md
- _posts/en/meetings/2015-11-19-meeting.md
- _posts/en/meetings/2015-11-26-meeting.md
- _posts/en/meetings/2015-12-03-meeting.md
- _posts/en/meetings/2015-12-10-meeting.md
- _posts/en/meetings/2015-12-17-meeting.md
- _posts/en/meetings/2016-01-07-meeting.md
- _posts/en/pages/2016-01-01-meetings.md
- _posts/es/pages/2016-01-01-meetings.md
- _posts/fr/pages/2016-01-01-meetings.md
- _posts/it/pages/2016-01-01-meetings.md
- _posts/ru/pages/2016-01-01-meetings.md
- _posts/zh_CN/pages/2016-01-01-meetings.md
- _posts/zh_TW/pages/2016-01-01-meetings.md
renders /en/meetings #18
todos
> Introduce weekly dev meeting summaries

- _layouts/home.html
- _layouts/post-index.html
> Show English posts when no translations are available.

- CNAME
This will be merged on January 15th after 15:00UTC
> Switch domain name

- _posts/en/meetings/2016-01-14-meeting.md
We can add the summary afterwards.
> Add IRC meeting 2016-01-14

- _posts/en/meetings/2015-10-01-meeting.md
- _posts/en/meetings/2015-10-08-meeting.md
- _posts/en/meetings/2015-10-15-meeting.md
- _posts/en/meetings/2015-10-22-meeting.md
- _posts/en/meetings/2015-10-29-meeting.md
- _posts/en/meetings/2015-11-05-meeting.md
- _posts/en/meetings/2015-11-12-meeting.md
- _posts/en/meetings/2015-11-19-meeting.md
- _posts/en/meetings/2015-11-26-meeting.md
- _posts/en/meetings/2015-12-03-meeting.md
- _posts/en/meetings/2015-12-10-meeting.md
- _posts/en/meetings/2015-12-17-meeting.md
- _posts/en/meetings/2016-01-07-meeting.md
> Fix wrong name

- _includes/_related.html
- _layouts/post.html
> Fix related-articles (move from header to post area)

- _data/navigation.yml
- _posts/en/pages/2016-01-13-supported-bips.md
> Add supported BIPs page

- _includes/_author-bio.html
Mentioned by @MarcoFalke : https://github.com/bitcoin-core/website/pull/24#issuecomment-172465040
> Fix author-bio picture (empty white circle)

- _posts/en/pages/faq/2016-01-21-rbf-faq.md
> Add RBF FAQ

- _posts/en/pages/2016-01-18-segwit-wallet-dev.md
> WIP: Segwit wallet dev guide

- _posts/en/posts/2016-01-21-segwit-testnet.md
Todos
* Travis tests will fail until #55 is merged
> [blog] Launch of Segragated Witness Testnet

- _sass/page.scss
Testsite: https://coresitetest.jonasschnelli.ch/en/supporters/
Added some margin between the "Show your Support" element and the footer.
Broaden the supporters page a little bit, left / right align first and last col.
> Overhaul supporters page

- _posts/en/pages/2016-01-13-segwit-support.md
For ref:
Ledger: https://github.com/LedgerHQ/ledger-wallet-chrome/blob/master/app/libs/bitcoinjs-min.js
Samurai: https://www.reddit.com/r/Bitcoin/comments/3q2by8/samourai_releases_major_update_to_sentinel_watch/cwfh96d
> update depends table, remove white spaces

- _sass/page.scss
> Fix TOC top margin

- _sass/page.scss
Adds mouse-over state in subnavigation.
Testsite: https://coresitetest.jonasschnelli.ch
> black/inverted mouse-over state for subnavigation

- _posts/en/pages/2016-01-01-about.md
To facilitate translating with Transifex, every sentence should be kept on one line only.
This PR removes one extra line-break present in the 2016-01-01-about.md english page.
> In-sentence line-break removal for Transifex compatibility

- _data/navigation.yml
Add a separate entry in the FAQ menu for the Capacity Increases article.
> Fix FAQ menu to point to correct segwit FAQ.

- _posts/en/posts/2016-01-26-segwit-benefits.md
Fixes a remaining extra line-break in 2016-01-26-segwit-benefits.md
> Line break fix

- _posts/en/meetings/2015-12-03-meeting.md
> Change 2015-12-03 meeting to the correct one

- _includes/_meetings.html
Translations were not correctly displayed in meetings page.
> Meetings page translations fix

- _posts/en/pages/2016-01-13-segwit-support.md
> fixed minor typo

- _data/navigation.yml
- _data/translations.yml
Spanish sections for both files (navigation.yml, translations.yml)
> Nav translation

- _data/navigation.yml
Translation for the extended menu
> spanish translation

- _posts/en/posts/2015-12-07-ml-capacity-roadmap.md
Improves accessibility and this is really important content. Note it is backdated.
> Repost of Roadmap post to bitcoin-dev

- _posts/en/posts/2015-09-01-open-letter.md
Originally posted elsewhere because we didn't have our own website.
> Repost 2015-09-01 open letter

- _posts/en/posts/2016-02-23-release-0-12-0.md
I've gone through and corrected a few errors, and I think made the post a bit more clear.
> updated grammar for release post

- _posts/en/releases/2016-02-23-release-0.12.0.md
see https://github.com/bitcoin/bitcoin/pull/7617
> Sync 0.12 release notes with bitcoin/master

- _posts/en/meetings/2016-02-25-meeting.md
I swapped the logs and meetbot links. Also added the BIP 109 link.
Sorry for not noticing earlier.
> Correct 2016-02-25 meeting links

- _includes/_references.md
- _includes/pages/bips-list.md
- _posts/en/meetings/2016-03-03-meeting.md
- _posts/en/pages/2016-01-13-supported-bips.md
This introduces a central link reference file for _common_ references.
> Add references.md

- _includes/_references.md
- _posts/en/meetings/2016-03-17-meeting.md
I've done the old style of background-comments-conclusion.
Comments welcome, been out of the loop for a month so I might have missed information.
> Summary for 2016-03-17

- _includes/_references.md
- _posts/en/pages/2016-01-01-contribute.md
c.f. https://botbot.me/freenode/bitcoin-core-dev/2016-04-08/?msg=63751542&page=1 @jonasschnelli 
https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2016-April/000000.html @laanwj
> Update list information

- _data/authors.yml
- _posts/en/posts/2016-04-14-maintainer-appointed-marcofalke.md
See https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2016-April/000003.html
> Add MarcoFalke announcement

- _includes/pages/bips-list.md
- _posts/en/pages/2016-01-13-supported-bips.md
> Update list of supported BIPs

- _posts/en/posts/2016-04-15-release-0-12-1.md
- _posts/en/releases/2016-04-15-release-0.12.1.md
Release notes for 0.12.1
Todos
> 0.12.1 release notes and blog post

- _posts/en/pages/2016-01-18-segwit-wallet-dev.md
Update the segwit wallet dev guide to include details on segwit NODE_WITNESS service bit
> Update segwit dev guide with service bit

- _includes/_references.md
- _posts/en/meetings/2016-04-28-meeting.md
Couldn't find the report of the CTAES review. Would be nice to link it.
> Meeting summary for 2016-04-28

- _posts/en/posts/2016-06-07-compact-blocks-faq.md
Some better numbers from my updated node stats. My latest numbers are ridiculously good, but I'm not sure if that's luck or my node being fully warmed up.
> Rephrasing and updated stats

- _posts/en/posts/2016-06-21-csv-softfork-instructions.md
Written by @jl2012 and submitted by me on request
ping @harding
> Blog post for CSV activation

- _includes/_references.md
- _posts/en/meetings/2016-07-14-meeting.md
Not sure if the segwit conclusion is clear enough. Maybe should explicitly state: no feedback == no release
> Meeting summaries for 2016-07-14

- _posts/en/posts/2016-06-07-compact-blocks-faq.md
pull request requested at https://github.com/bitcoin-core/bitcoincore.org/commit/ebbd8a840c21517d24ea9304d3de9f1037859a65#commitcomment-18328893
> Link to permanent PR of reference implementation

- _posts/en/pages/2016-03-12-contact.md
> clarify contact page with support channel

- _posts/en/posts/2016-06-24-segwit-next-steps.md
> Another small typo: "the the"

- _posts/zh_CN/posts/2016-01-26-segwit-benefits.md
2016-01-26-segwit-benefits.md  simplified chinese zh_CN, please suggest only simplified chinese corrections
> 2016-01-26-segwit-benefits.md

- _data/navigation.yml
zh_CN simplified chinese menu edits
> zh_CN simplified chinese menu edits

- _includes/pages/segwit_support.md
> NBitcoin segwit ready

- _sass/variables.scss
Per post-merge comments on #231 this switches the bikeshed colours to green/yellow.
> Switch segwit adoption colours to green/yellow

- _posts/en/pages/2016-01-18-segwit-wallet-dev.md
> rewrite segwit wallet dev guide

- _includes/_references.md
- _posts/en/posts/2016-10-28-segwit-costs.md
I said in the #67 PR "It's a bit one-sided, in that it only lists benefits. I think maybe it would be better to include costs too"; but at the time I couldn't work out how to say anything intelligent on the topic. Now that segwit is able to be deployed and activated, it seems appropriate to revisit that.
I've separated each section as a separate commit to maybe make things a little easier to review/comment on.
> Add page with a technical overview of segwit costs and risk

- _data/segwitsupport.csv
> Add bitcoin-s to segwit support list 

- _data/segwitsupport.csv
Please add our project to the SegWit support list! Thx
> add Cryptobuyer to Segregated Witness Support list

- _data/segwitsupport.csv
The page said that it was not formatting correctly because not all lines had the same number of columns. I've added the missing commas to fix it.
> Added commas to make all lines have six columns

- _data/segwitsupport.csv
eg. new fields on tx: hash, vsize and witness
prod ready: https://api.smartbit.com.au/v1/blockchain/tx/1c9fd2ae997f14c4ecc5f265b58cc1162423fe3fd2174a2cd2c99dc47a48b097
testnet live: https://testnet-api.smartbit.com.au/v1/blockchain/tx/10bbdf7e9301bc21f1da8684f25fd66bc1314904c30da25a8ebf967c58c89269
Many other endpoints also updated.
> smartbit ready for segwit

- _data/segwitsupport.csv
Probably the most wagered at bitcoin casino for the last few months
> Add bustabit to segwit support

- _posts/en/pages/2016-10-26-segwit-upgrade-guide.md
See https://github.com/ckolivas/cgminer/pull/699#issuecomment-259007261
> CGminer segwit support has been merged

- _data/segwitsupport.csv
We're ready for SegWit! Added at last line.
> Update list to add Xotika.tv

- _data/segwitsupport.csv
P2Pool requires a hard fork for SegWit support. Code is currently being tested.
> P2Pool ready=no

- _data/segwitsupport.csv
This pull request updates the SW status of Omni Core to WIP.
We're currently testing a 0.13.1 based release internally.
> Update SW status for Omni Core to WIP

- _data/segwitsupport.csv
Add [NiceHash Solo](https://solo.nicehash.com/) for SegWit support.
> add NiceHash Solo for SegWit support

- _data/segwitsupport.csv
CoinCorner (Bitcoin Exchange) plans to support segwit, currently WIP
> Addition of CoinCorner

- _data/segwitsupport.csv
LocalBitcoins is ready for SegWit
> Added LocalBitcoins column

- _data/segwitsupport.csv
> added blockonomics to segwitsupport.csv

- _data/segwitsupport.csv
Ready and supporting segwit 100%
> Added Paxful that supports segwit

- _includes/_references.md
- _posts/en/meetings/2016-12-22-meeting.md
Hopefully this fixes the weird characters issue
> Meeting summaries 2016-12-22 v2

- _posts/en/posts/2017-01-03-release-0.13.2.md
- _posts/en/releases/2017-01-03-release-0.13.2.md
> Add blog post and release notes for 0.13.2

- _data/segwitsupport.csv
Walltime is ready, please merge this pull request.
> Walltime is ready now.

- _data/segwitsupport.csv
> Added segwit planned entry for Yogh

- _data/segwitsupport.csv
A visual block explorer. All ready to display segwit transactions.
> Added learnmeabitcoin.com to segwitsupport.csv

- _includes/_references.md
- _posts/en/meetings/2017-02-16-meeting.md
Two commits:
1. I sorted the names in `_references.md` so that I could look them up more easily.  I also removed duplicate entries for Pavel (but left in duplicate entries for Jorge because they included his last name spelled with and without the accent mark).
2. Meeting notes for 2017-02-16 (please ignore the branch name, which has the wrong year).
Preview:
> Meeting notes for 2017-02-16

- _data/segwitsupport.csv
This adds Otika.tv to Segwit support list and updates some of the terminology related to XotikaTV
> Updates to Xotika & Otika

- _includes/_references.md
- _posts/en/meetings/2017-02-23-meeting.md
Notes from last week's meeting.
> Meeting notes: 2017-02-23

- _data/segwitsupport.csv
Electrum 2.8 has Testnet support for segwit
> Update segwitsupport.csv wrt Electrum -> ready

- _posts/en/meetings/2017-03-02-meeting.md
This corrects the description for the motivation for a soft fork to increase the minimum difficulty.  Many thanks to @gmaxwell for his reply to me on Reddit regarding this: https://www.reddit.com/r/Bitcoin/comments/5z5lbt/bitcoin_core_irc_meeting_summary_march_2_2017/devyzw7/
> Meeting 2017-03-02: correct description of minimum difficulty potential soft fork

- _data/segwitsupport.csv
Australian Bitcoin ATMs ready for SegWit
> added BitRocket.co ATM operator as SegWit ready

- _data/segwitsupport.csv
This PR is to signal HolyTransaction's support on https://bitcoincore.org/en/segwit_adoption/
> Add HolyTransaction to segwitsupport.csv

- _posts/en/meetings/2017-04-06-meeting.md
> Fix spelling

- _data/segwitsupport.csv
SegWit is WIP (e.g. https://github.com/CounterpartyXCP/counterparty-lib/pull/965)
> Add Counterparty

- _includes/_references.md
- _posts/en/meetings/2017-04-20-meeting.md
- _posts/en/meetings/2017-04-27-meeting.md
Fixed a link in previous meeting as well.
> Meeting summaries 2017-04-27

- _data/segwitsupport.csv
Added and updated a few companies.
> Update Segwit Support

- _includes/_references.md
- _posts/en/meetings/2017-05-11-meeting.md
Sorry for the delay, I'll try to get up to date at some point...
> meeting summaries 2017-05-11

- _posts/en/pages/2016-10-26-segwit-upgrade-guide.md
> Clarify upgrade language

- _posts/en/posts/2017-08-18-btc1-misleading-statements.md
This post was written collaboratively after the IRC meeting yesterday and has been reviewed by ~all relevant parties.
> Add post correcting some misunderstandings around btc1/segwit2x

- _data/segwitsupport.csv
Update segwitsupport.csv with bitcoinML library; BitcoinML is a "Bitcoin data-structures library for OCaml", written in OCaml; the library now supports segwit transaction format.
> Update segwitsupport.csv with bitcoinML library

- _data/languages.yml
- _data/navigation.yml
- _data/translations.yml
- _posts/ja/pages/2016-01-01-index.md
- _posts/ja/pages/2016-03-21-rss.md
- _posts/ja/posts/2017-08-18-btc1-misleading-statements-ja.md
- assets/feeds/feed-ja.xml
- assets/meeting_rss/rss-ja.xml
- assets/rss/rss-ja.xml
add btc1-misleading-statements translation for japanese and japanese language.
> Add japanese translation btc1-misleading-statements

- _data/segwitsupport.csv
Reference: https://twitter.com/blockonomics_co/status/898817116614213632
> Update blockonomics segwit adoption status

- _data/segwitsupport.csv
Support is _ready_ as per https://github.com/paritytech/parity-bitcoin/pull/444
I allowed myself to sort the list alphabetically.
> Add Parity Bitcoin to list of segwit-support.

- contrib/verify-commits/pre-push-hook.sh
Cause this failed a few times now :(.
> Fix pre-push-hook repo match.

- _data/segwitsupport.csv
Added bitsler.com on list of companies/sites that supports Segwit
> Bitsler.com is Segwit ready

- _data/segwitsupport.csv
- _posts/en/pages/2016-01-13-segwit-support.md
- Remove miner signalling as it's activated now
- Add Bitstmap support at their request
> Update segwit adoption page

- _data/segwitsupport.csv
'libbitc' mistyped as 'ibbitc'
> Fix typo in segwitsupport.csv

- _includes/_references.md
- _posts/en/meetings/2017-10-26-meeting.md
This commit is for the meeting notes for the Bitcoin Core Developer meeting on 2017-10-26.
> Meeting Notes for 2017-10-26 Bitcoin Core Developer Meeting

- _posts/en/meetings/2017-11-02-meeting.md
This is the Bitcoin Core meeting for 2017-11-02, sorry for taking so long the rest will be here after my finals are completed.
> Addition of the 2017-11-02 Meeting 

- _data/segwitsupport.csv
- _posts/en/pages/2016-01-13-segwit-support.md
- _posts/zh_CN/pages/2016-01-13-segwit-support.md
Updates some services to deployed status, update some BitGo customer examples.
> update service segwit statuses

- _data/segwitsupport.csv
We had the first non-P2SH segwit transaction on Bitcoin mainnet in the world, and were ready on day one.
> add Bitbank (Japan)

- _data/segwitsupport.csv
Electrum already implemented SegWit in his wallets for PC
> Change Electrum Wallet to deployed status.

- _data/segwitsupport.csv
It corrects rendering errors in CSV preview on Github:
<https://github.com/bitcoin-core/bitcoincore.org/blob/master/_data/segwitsupport.csv>
> Fix CSV syntax errors

- _releases/0.16.0.md
I've never created a release page on bitcoincore.org before, so please review carefully.
> Bitcoin Core 0.16.0

- _includes/_references.md
- _posts/en/meetings/2018-04-12-meeting.md
Preview: http://dg1.dtrt.org/en/meetings/2018/04/12
> Meetings: add 2018-04-12

- _includes/_references.md
- _includes/pages/bips-list.md
- _posts/en/pages/2016-01-18-segwit-wallet-dev.md
Found a few typos and updated information about segwit activation and Bech32 native address types.
> Updating segwit_wallet_dev info

- _includes/_references.md
- _posts/en/meetings/2018-05-10-meeting.md
Preview: http://dg2.dtrt.org/en/meetings/2018/05/10/
> Meetings: add 2018-05-10

- _includes/_references.md
- _posts/en/meetings/2018-05-17-meeting.md
Preview: http://dg1.dtrt.org/en/meetings/2018/05/17/
> Meetings: add 2018-05-17

- _includes/link-to-issues.md
- _posts/en/meetings/2018-05-24-meeting.md
- _posts/en/meetings/2018-05-31-meeting.md
- [5/24 preview](http://dg2.dtrt.org/en/meetings/2018/05/24/)
- [5/31 preview](http://dg2.dtrt.org/en/meetings/2018/05/31/)
- The typical "Comedic relic" section was deliberately omitted.  Y'all were all business this week.
> Meetings: add 2018-05-24 and 2018-05-31

- _includes/_references.md
- _posts/en/meetings/2018-06-07-meeting.md
Preview: http://dg1.dtrt.org/en/meetings/2018/06/07/
> Meetings: add 2018-06-07

- _posts/en/meetings/2018-06-14-meeting.md
Preview: http://dg1.dtrt.org/en/meetings/2018/06/14/
> Meetings: add 2018-06-14

- _includes/references.md
- _posts/en/meetings/2018-06-28-meeting.md
Preview: http://dg0.dtrt.org/en/meetings/2018/06/28/
No humor this week, so no comedic relief section.
> Meetings: add 2018-06-28

- _posts/en/meetings/2018-07-26-meeting.md
Preview: http://dg1.dtrt.org/en/meetings/2018/07/26/
> Meetings: add 2018-07-26

- _posts/en/posts/2018-07-29-release-0.16.2.md
- _releases/0.16.2.md
Suggested by @jnewbery on #582
> 0.16.2 release: fix nits in blog and release posts

- _includes/references.md
- _posts/en/meetings/2018-08-02-meeting.md
Preview: http://dg0.dtrt.org/en/meetings/2018/08/02/
> Meetings: add 2018-08-03

- _posts/en/posts/2018-09-20-notice.md
Only change from text I received is the excerpt and addition of bullet point markup.
> Posts: full disclosure for CVE-2018-17144

- _posts/en/posts/2018-09-20-notice.md
This cherry picks the non-controversial commits from #608 
Edit: upon closer inspection, I discovered a typo and that one of the commits make the text confusing, so I reduced to just the minimal requested changes by earlz.
> Update CVE-2018-17144 credits

- _posts/en/posts/2018-10-02-release-0.17.0.md
Reported by e4xit on Freenode IRC.
> Releases 0.17: fix typo

- _releases/0.17.0.md
Add magnet link for 0.17.0 release. Also bump the release date to today.
> Add magnet link for 0.17.0 release

- _posts/ja/pages/2017-01-01-download.md
Apply 0387192 and 37dbc30 to the Japanese download page.
> Upgrade japanese download page to version 2

- _data/navigation.yml
- _posts/ja/posts/2016-01-26-segwit-benefits.md
- _posts/ja/posts/2018-02-26-release-0.16.0.md
- _posts/ja/releases/2018-02-26-release-0.16.0.md
Closes #511 
Closes #516 
This rebases the above PRs and makes some minor tweaks to the content so that they'll merge cleanly.
> Translations: update old unmerged translations to pass new tests

- _includes/references.md
- _posts/en/meetings/2018-11-01-meeting.md
Meeting summary was contributed by the BitDevs NYC community :two_hearts:
> Meetings: add 2018-11-02

- contrib/devtools/README.md
- contrib/devtools/people-present.sh
This is useful when creating a meeting summary.
Script by @harding.
> [contrib] Add script to turn 'people present' list into table

- _includes/templates/download.html
- _posts/en/pages/2017-01-01-download.md
- _posts/ja/pages/2017-01-01-download.md
> Remove download references to PPA

- CONTRIBUTING.md
- README.md
> doc: Remove link to unused transifex

- _posts/en/posts/2017-03-23-schnorr-sigagg.md
> fix schnorr link to elements project

- _posts/en/posts/2019-11-08-CVE-2017-18350.md
Not sure if this warrants a bitcoincore.org post or not...
> Posts: CVE-2017-18350 disclosure

- _posts/en/posts/2020-03-27-hidden-service.md
> Add post about Tor hidden service

- _posts/en/posts/2020-08-01-release-0.20.1.md
- _releases/0.20.1.md
Todos:
Note: tests expect to fail until the binaries have been uploaded to `/bin/`. After that's done, restart Travis and it should pass.
CC: Sjors to whitelist the magnet hash on his torrent tracker (e.g. https://github.com/bitcoin-core/bitcoincore.org/pull/698#issuecomment-596678739 )
> Releases: add 0.20.1

- _posts/ja/pages/2016-01-01-about.md
Updated japanese translation contributor list on about page to follow #719
> Updated japanese translation contributor list on about page

- _posts/en/pages/2016-01-01-meetings.md
add ical format of the meeting camendar
> add ical format of the meeting camendar

- _data/stats.yml
> Bump Approx disk size to 400 Gb

- _releases/0.19.1.md
- _releases/0.20.0.md
- _releases/0.20.1.md
> Add torrent link to 0.19.1 and 0.20.x release pages

- _includes/download_release.html
- _includes/templates/download.html
- _releases/0.21.1.md
Revert commit 13572bcdfb4a6ba15f4c3c6ea7436f5eca02c45d and add torrent magnet link for 0.21.1.
> Releases: Add 0.21.1 torrent

- _includes/references.md
- _posts/en/pages/2016-01-01-meetings.md
Fixes https://github.com/bitcoin-core/bitcoincore.org/commit/259fd8bb6db5333863bd1e688fa9efa1ebfd9941#r51521757
> doc: Fix IRC links

- _posts/en/posts/2021-09-29-release-0.21.2.md
- _releases/0.21.2.md
Adds a release announcement for 0.21.2. Modeled after #792.
> Bitcoin Core 0.21.2

- _includes/dev-keys.md
Add fanquake's key fingerprint to the contact page.
> Add fanquake dev key

- _config.yml
See https://github.com/bitcoin/bitcoin/pull/23466
> Suggest `keys.openpgp.org` as keyserver

- _data/languages.yml
- _data/navigation.yml
- _data/translations.yml
- _posts/es/pages/2016-01-01-about.md
- _posts/es/pages/2016-01-01-index.md
- _posts/es/pages/2016-01-01-releases.md
- _posts/es/pages/2016-03-21-rss.md
- _posts/es/pages/2017-01-01-download.md
- _posts/es/posts/2021-09-29-release-0.21.2.md
- _posts/es/releases/2021-09-29-release-0.21.2.md
- assets/feeds/feed-es.xml
- assets/meeting_rss/rss-es.xml
- assets/rss/releases-es.xml
- assets/rss/rss-es.xml
Attempts to exactly mimic #810 for spanish language,
meaning format issues in #810 directly apply here as well.
Untested at the time of submitting.
> Add spanish translation of 0.21.2

- _posts/en/posts/2016-02-26-zkcp.md
Transaction links are not actually broken, but soon to be.
> Fix broken links in the ZKCP article

- _posts/es/pages/2017-01-01-download.md
Complete 33309148 applying 353e34ee to it.
This change was missing because concurrent changes.
> Solve merge conflict on the Spanish translation

- _config.yml
- _data/authors.yml
- _includes/author-bio.html
- _includes/head.html
- _includes/scripts.html
- _layouts/feed.xml
Google plus was shut down long ago, so no need to keep any references to it. Also, remove other google settings.
> remove google plus

- _posts/en/pages/2016-01-01-meetings.md
> meeting logs: update link to erisian logs

- _posts/en/posts/2022-12-15-release-22.1.md
- _releases/22.1.md
> Bitcoin Core 22.1

- _posts/en/posts/2023-05-18-release-24.1.md
- _releases/24.1.md
Add release pages for Bitcoin Core `v24.1`.
> Bitcoin Core 24.1

- _posts/en/posts/2023-05-18-release-23.2.md
- _releases/23.2.md
Add release pages for Bitcoin Core v23.2.
> Bitcoin Core 23.2

- _posts/en/posts/2023-10-19-release-25.1.md
- _releases/25.1.md
Release annoucement for `25.1`.
> Bitcoin Core 25.1

- _posts/en/posts/2023-10-26-release-24.2.md
- _releases/24.2.md
> Bitcoin Core 24.2

- _data/stats.yml
> stats: update datadir_gb & pruned_gb

- _posts/en/posts/2024-04-02-release-26.1.md
- _releases/26.1.md
> Bitcoin Core 26.1

- .cirrus.yml
Fixes https://github.com/bitcoin-core/bitcoincore.org/pull/987#issuecomment-2061385929
https://cirrus-ci.com/task/4947246632927232 is a sample run on a slightly modified version so that it would work on this pr branch.
> ci: Fix verify commits ci

- _posts/en/posts/2024-06-17-release-27.1.md
- _releases/27.1.md
> Bitcoin Core 27.1

- _posts/en/posts/2024-07-09-release-26.2.md
- _releases/26.2.md
final changes PR: https://github.com/bitcoin/bitcoin/pull/30376
> Bitcoin Core 26.2

- _posts/en/posts/2024-07-03-disclose-bip70-crash.md
- _posts/en/posts/2024-07-03-disclose_already_asked_for.md
Makes the version in the timeline fit the version in the title
> Update censorship advisory for versions to match

- _posts/en/posts/2024-07-31-disclose-addrman-int-overflow.md
- _posts/en/posts/2024-07-31-disclose-upnp-oom.md
See: https://github.com/bitcoin-core/bitcoincore.org/pull/1049/files#r1698859796.
> Use consistent date format for advisories

- _posts/en/posts/2024-09-18-disclose-headers-oom.md
There was one security vulnerability fixed in v24.0.1.
Thanks to Pieter Wuille and Suhas Daftuar for their help in writing this up.
> Security advisories for vulnerabilities fixed in v24.0.1

- _posts/en/posts/2024-11-04-release-27.2.md
- _releases/27.2.md
> Bitcoin Core 27.2

- _posts/en/posts/2025-03-31-disclose-cve-2024-52919.md
- _posts/ja/posts/2025-03-31-disclose-cve-2024-52919.md
and fix small typo in the english post.
> Add japanese translation for security advisory for remaining CVE-2024-52919 issue

- _posts/en/posts/2025-06-06-relay-statement.md
This publishes the statement on the relation between Bitcoin Core development and transaction relay that has been discussed the past few weeks.
Feel free to comment if you'd like to add your name (and what form you prefer, real name/nickname/...)
> Add statement on transaction relay

- _config.yml
- _data/navigation.yml
- _includes/footer.html
- _includes/references.md
- _posts/en/pages/2016-01-15-lifecycle.md
- _posts/en/pages/2016-03-12-contact.md
- _posts/en/pages/2017-01-01-twitter-impersonation.md
- _posts/ja/pages/2016-03-12-contact.md
- contrib/qa/test-binary-availability.sh
Also remove references to Travis.
Update link in lifestyle.
> impersonation: switch Twitter for X

- _posts/en/posts/2025-06-26-release-28.2.md
- _releases/28.2.md
Blog & release notes for `28.2`.
> Bitcoin Core 28.2
